//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.LocationData
{
	using System; 
	using System.ComponentModel;

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class LocationData { }
#else

	public class LocationData : INotifyPropertyChanged
	{
		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

		public LocationData()
		{
			try
			{
				Uri resourceUri = new Uri("/DiveLog;component/SampleData/LocationData/LocationData.xaml", UriKind.RelativeOrAbsolute);
				System.Windows.Application.LoadComponent(this, resourceUri);
			}
			catch
			{
			}
		}

		private ItemCollection _Collection = new ItemCollection();

		public ItemCollection Collection
		{
			get
			{
				return this._Collection;
			}
		}
	}

	public class Item : INotifyPropertyChanged
	{
		public event PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}

		private string _LocationName = string.Empty;

		public string LocationName
		{
			get
			{
				return this._LocationName;
			}

			set
			{
				if (this._LocationName != value)
				{
					this._LocationName = value;
					this.OnPropertyChanged("LocationName");
				}
			}
		}

		private System.Windows.Media.ImageSource _LocationImage = null;

		public System.Windows.Media.ImageSource LocationImage
		{
			get
			{
				return this._LocationImage;
			}

			set
			{
				if (this._LocationImage != value)
				{
					this._LocationImage = value;
					this.OnPropertyChanged("LocationImage");
				}
			}
		}

		private string _Country = string.Empty;

		public string Country
		{
			get
			{
				return this._Country;
			}

			set
			{
				if (this._Country != value)
				{
					this._Country = value;
					this.OnPropertyChanged("Country");
				}
			}
		}
	}

	public class ItemCollection : System.Collections.ObjectModel.ObservableCollection<Item>
	{ 
	}
#endif
}
